name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.11.1
        coq-version:
          - 8.11.2
          - 8.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add coq ${{ matrix.coq-version }}

      - run: opam pin add coq-of-ocaml.dev . --no-action

      - run: opam depext coq-of-ocaml --yes --with-doc --with-test

      - run: opam install coq-of-ocaml --deps-only --with-doc --with-test

      - run: opam install coq-of-ocaml --verbose --with-doc --with-test
